openapi: 3.0.1
info:
  version: 1.0.0
  title: ElektroGo
  description: "Documentació OpenAPI per a l'API REST desenvolupada a partir de l'aplicació **ElektroGo**. <br> Per tal de poder executar les operacions cal estar conectat a la VPN de l'UPC. Totes les operacions requereixen d'una api_key. En cas de no tenir-ne la podeu solicitar a qualsevol membre de l'equip."
servers:
  - url: 'http://10.4.41.58:8080/'
paths:
  /car-pooling/byCoord:
    get:
      tags:
      - Car pooling
      summary: Donades unes coordenades (latitude i longitude) rep la informació de tots els punts de car pooling vigents dins d'un radi indicat per parametre (en km).
      operationId: getCarPooling
      parameters:
      - name: latitude
        in: query
        description: Coordenada latitud de l'origen
        required: true
        schema:
          type: number
      - name: longitude
        in: query
        description: Coordenada longitude de l'origen
        required: true
        schema:
          type: number
      - name: Radi
        in: query
        description: Radi de l'àrea a analitzar (en km).
        required: true
        schema:
          type: number
      - name: key
        in: query
        description: api_key per poder fer servir la API.
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CarPooling'
        400:
          description: 'Error: Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error400'
        401:
          description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
components:
  schemas:
    CarPooling:
      type: object
      properties:
        id:
          type: integer
          example: 1
        startDate:
          type: string
          format: date (yyyy-mm-dd)
          example: "2022-01-20"
        startTime:
          type: string
          format: time 24h
          example: "12:00:00"
        offeredSeats:
          type: integer
          example: 4
        occupiedSeats:
          type: integer
          example: 2
        restrictions:
          type: string
          example: 'No es pot fumar dins del vehícle'
        details:
          type: string
          example: 'Acostumo a conduir bastant ràpid'
        vehicleNumberPlate:
          type: string
          example: "2001MMO"
        origin:
          type: string
          example: "FIB Facultat d'Informàtica de Barcelona, C/Jordi Girona, 1-3, 08034 Barcelona"
        destination:
          type: string
          example: "Estadi Montilivi, Avinguda de Montilivi, 141, 17003 Girona"
        username:
          type: string
          example: "PolB"
        cancelDate: 
          type: string
          format: date (yyyy-mm-dd)
          example: "2022-01-19"
        latitudeOrigin: 
          type: number
          example: 41.3894
        longitudeOrigin:
          type: number
          example: 2.1134
        latitudeDestination: 
          type: number
          example: 41.9611
        longitudeDestination:
          type: number
          example: 2.8279
        
        
          
    ErrorResult:
      type: object
      properties:
        status:
          type: integer
          enum: [400, 401, 404]
        error: 
          type: string
          enum: ["Bad Request", "Unauthorized", "Not found"]
        message: 
          type: string
  examples:
    error400:
      value:
        status: 400
        error: "Bad Request"
        message: "Missing parameter"
    error401:
      value:
        status: 401
        error: "Unauthorized"
        message: "Unvalid api key"
    error404:
      value:
        status: 404
        error: "Not found"
        message: "There are no trips in the radius specified"
